package com.parses.dao.model;

import java.util.Date;

public class CapitalTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_capital_type
     *
     * @mbg.generated
     */
    private String capitalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_capital_code
     *
     * @mbg.generated
     */
    private String capitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_match_target_code
     *
     * @mbg.generated
     */
    private String matchTargetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_match_target_rank_level
     *
     * @mbg.generated
     */
    private String matchTargetRankLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_repayment_formula_no
     *
     * @mbg.generated
     */
    private String repaymentFormulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_repayment_formula_name
     *
     * @mbg.generated
     */
    private String repaymentFormulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_clearing_formula_no
     *
     * @mbg.generated
     */
    private String clearingFormulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_clearing_formula_name
     *
     * @mbg.generated
     */
    private String clearingFormulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_is_support_accelerate
     *
     * @mbg.generated
     */
    private String isSupportAccelerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_repurchase_calculation_mode
     *
     * @mbg.generated
     */
    private String repurchaseCalculationMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_fee_template_no
     *
     * @mbg.generated
     */
    private String feeTemplateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_fee_code
     *
     * @mbg.generated
     */
    private String feeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_template.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_id
     *
     * @return the value of t_pec_capital_template.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_id
     *
     * @param id the value for t_pec_capital_template.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_version
     *
     * @return the value of t_pec_capital_template.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_version
     *
     * @param version the value for t_pec_capital_template.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_capital_type
     *
     * @return the value of t_pec_capital_template.f_capital_type
     *
     * @mbg.generated
     */
    public String getCapitalType() {
        return capitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_capital_type
     *
     * @param capitalType the value for t_pec_capital_template.f_capital_type
     *
     * @mbg.generated
     */
    public void setCapitalType(String capitalType) {
        this.capitalType = capitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_capital_code
     *
     * @return the value of t_pec_capital_template.f_capital_code
     *
     * @mbg.generated
     */
    public String getCapitalCode() {
        return capitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_capital_code
     *
     * @param capitalCode the value for t_pec_capital_template.f_capital_code
     *
     * @mbg.generated
     */
    public void setCapitalCode(String capitalCode) {
        this.capitalCode = capitalCode == null ? null : capitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_match_target_code
     *
     * @return the value of t_pec_capital_template.f_match_target_code
     *
     * @mbg.generated
     */
    public String getMatchTargetCode() {
        return matchTargetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_match_target_code
     *
     * @param matchTargetCode the value for t_pec_capital_template.f_match_target_code
     *
     * @mbg.generated
     */
    public void setMatchTargetCode(String matchTargetCode) {
        this.matchTargetCode = matchTargetCode == null ? null : matchTargetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_match_target_rank_level
     *
     * @return the value of t_pec_capital_template.f_match_target_rank_level
     *
     * @mbg.generated
     */
    public String getMatchTargetRankLevel() {
        return matchTargetRankLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_match_target_rank_level
     *
     * @param matchTargetRankLevel the value for t_pec_capital_template.f_match_target_rank_level
     *
     * @mbg.generated
     */
    public void setMatchTargetRankLevel(String matchTargetRankLevel) {
        this.matchTargetRankLevel = matchTargetRankLevel == null ? null : matchTargetRankLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_repayment_formula_no
     *
     * @return the value of t_pec_capital_template.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaNo() {
        return repaymentFormulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_repayment_formula_no
     *
     * @param repaymentFormulaNo the value for t_pec_capital_template.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaNo(String repaymentFormulaNo) {
        this.repaymentFormulaNo = repaymentFormulaNo == null ? null : repaymentFormulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_repayment_formula_name
     *
     * @return the value of t_pec_capital_template.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaName() {
        return repaymentFormulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_repayment_formula_name
     *
     * @param repaymentFormulaName the value for t_pec_capital_template.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaName(String repaymentFormulaName) {
        this.repaymentFormulaName = repaymentFormulaName == null ? null : repaymentFormulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_clearing_formula_no
     *
     * @return the value of t_pec_capital_template.f_clearing_formula_no
     *
     * @mbg.generated
     */
    public String getClearingFormulaNo() {
        return clearingFormulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_clearing_formula_no
     *
     * @param clearingFormulaNo the value for t_pec_capital_template.f_clearing_formula_no
     *
     * @mbg.generated
     */
    public void setClearingFormulaNo(String clearingFormulaNo) {
        this.clearingFormulaNo = clearingFormulaNo == null ? null : clearingFormulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_clearing_formula_name
     *
     * @return the value of t_pec_capital_template.f_clearing_formula_name
     *
     * @mbg.generated
     */
    public String getClearingFormulaName() {
        return clearingFormulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_clearing_formula_name
     *
     * @param clearingFormulaName the value for t_pec_capital_template.f_clearing_formula_name
     *
     * @mbg.generated
     */
    public void setClearingFormulaName(String clearingFormulaName) {
        this.clearingFormulaName = clearingFormulaName == null ? null : clearingFormulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_is_support_accelerate
     *
     * @return the value of t_pec_capital_template.f_is_support_accelerate
     *
     * @mbg.generated
     */
    public String getIsSupportAccelerate() {
        return isSupportAccelerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_is_support_accelerate
     *
     * @param isSupportAccelerate the value for t_pec_capital_template.f_is_support_accelerate
     *
     * @mbg.generated
     */
    public void setIsSupportAccelerate(String isSupportAccelerate) {
        this.isSupportAccelerate = isSupportAccelerate == null ? null : isSupportAccelerate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_repurchase_calculation_mode
     *
     * @return the value of t_pec_capital_template.f_repurchase_calculation_mode
     *
     * @mbg.generated
     */
    public String getRepurchaseCalculationMode() {
        return repurchaseCalculationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_repurchase_calculation_mode
     *
     * @param repurchaseCalculationMode the value for t_pec_capital_template.f_repurchase_calculation_mode
     *
     * @mbg.generated
     */
    public void setRepurchaseCalculationMode(String repurchaseCalculationMode) {
        this.repurchaseCalculationMode = repurchaseCalculationMode == null ? null : repurchaseCalculationMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_fee_template_no
     *
     * @return the value of t_pec_capital_template.f_fee_template_no
     *
     * @mbg.generated
     */
    public String getFeeTemplateNo() {
        return feeTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_fee_template_no
     *
     * @param feeTemplateNo the value for t_pec_capital_template.f_fee_template_no
     *
     * @mbg.generated
     */
    public void setFeeTemplateNo(String feeTemplateNo) {
        this.feeTemplateNo = feeTemplateNo == null ? null : feeTemplateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_fee_code
     *
     * @return the value of t_pec_capital_template.f_fee_code
     *
     * @mbg.generated
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_fee_code
     *
     * @param feeCode the value for t_pec_capital_template.f_fee_code
     *
     * @mbg.generated
     */
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode == null ? null : feeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_created_time
     *
     * @return the value of t_pec_capital_template.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_created_time
     *
     * @param createdTime the value for t_pec_capital_template.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_modified_time
     *
     * @return the value of t_pec_capital_template.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_modified_time
     *
     * @param modifiedTime the value for t_pec_capital_template.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_template.f_operater_name
     *
     * @return the value of t_pec_capital_template.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_template.f_operater_name
     *
     * @param operaterName the value for t_pec_capital_template.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}