package com.parses.dao.model;

import java.util.Date;

public class CapitalEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_capital_no
     *
     * @mbg.generated
     */
    private String capitalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_current_mirror_no
     *
     * @mbg.generated
     */
    private String currentMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_template_no
     *
     * @mbg.generated
     */
    private String templateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_template_mirror_no
     *
     * @mbg.generated
     */
    private String templateMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_capital_code
     *
     * @mbg.generated
     */
    private String capitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_capital_name
     *
     * @mbg.generated
     */
    private String capitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_capital_member_no
     *
     * @mbg.generated
     */
    private String capitalMemberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_capital_status
     *
     * @mbg.generated
     */
    private Integer capitalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_id
     *
     * @return the value of t_pec_capital.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_id
     *
     * @param id the value for t_pec_capital.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_version
     *
     * @return the value of t_pec_capital.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_version
     *
     * @param version the value for t_pec_capital.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_capital_no
     *
     * @return the value of t_pec_capital.f_capital_no
     *
     * @mbg.generated
     */
    public String getCapitalNo() {
        return capitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_capital_no
     *
     * @param capitalNo the value for t_pec_capital.f_capital_no
     *
     * @mbg.generated
     */
    public void setCapitalNo(String capitalNo) {
        this.capitalNo = capitalNo == null ? null : capitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_current_mirror_no
     *
     * @return the value of t_pec_capital.f_current_mirror_no
     *
     * @mbg.generated
     */
    public String getCurrentMirrorNo() {
        return currentMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_current_mirror_no
     *
     * @param currentMirrorNo the value for t_pec_capital.f_current_mirror_no
     *
     * @mbg.generated
     */
    public void setCurrentMirrorNo(String currentMirrorNo) {
        this.currentMirrorNo = currentMirrorNo == null ? null : currentMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_template_no
     *
     * @return the value of t_pec_capital.f_template_no
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_template_no
     *
     * @param templateNo the value for t_pec_capital.f_template_no
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_template_mirror_no
     *
     * @return the value of t_pec_capital.f_template_mirror_no
     *
     * @mbg.generated
     */
    public String getTemplateMirrorNo() {
        return templateMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_template_mirror_no
     *
     * @param templateMirrorNo the value for t_pec_capital.f_template_mirror_no
     *
     * @mbg.generated
     */
    public void setTemplateMirrorNo(String templateMirrorNo) {
        this.templateMirrorNo = templateMirrorNo == null ? null : templateMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_capital_code
     *
     * @return the value of t_pec_capital.f_capital_code
     *
     * @mbg.generated
     */
    public String getCapitalCode() {
        return capitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_capital_code
     *
     * @param capitalCode the value for t_pec_capital.f_capital_code
     *
     * @mbg.generated
     */
    public void setCapitalCode(String capitalCode) {
        this.capitalCode = capitalCode == null ? null : capitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_capital_name
     *
     * @return the value of t_pec_capital.f_capital_name
     *
     * @mbg.generated
     */
    public String getCapitalName() {
        return capitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_capital_name
     *
     * @param capitalName the value for t_pec_capital.f_capital_name
     *
     * @mbg.generated
     */
    public void setCapitalName(String capitalName) {
        this.capitalName = capitalName == null ? null : capitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_capital_member_no
     *
     * @return the value of t_pec_capital.f_capital_member_no
     *
     * @mbg.generated
     */
    public String getCapitalMemberNo() {
        return capitalMemberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_capital_member_no
     *
     * @param capitalMemberNo the value for t_pec_capital.f_capital_member_no
     *
     * @mbg.generated
     */
    public void setCapitalMemberNo(String capitalMemberNo) {
        this.capitalMemberNo = capitalMemberNo == null ? null : capitalMemberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_capital_status
     *
     * @return the value of t_pec_capital.f_capital_status
     *
     * @mbg.generated
     */
    public Integer getCapitalStatus() {
        return capitalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_capital_status
     *
     * @param capitalStatus the value for t_pec_capital.f_capital_status
     *
     * @mbg.generated
     */
    public void setCapitalStatus(Integer capitalStatus) {
        this.capitalStatus = capitalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_created_time
     *
     * @return the value of t_pec_capital.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_created_time
     *
     * @param createdTime the value for t_pec_capital.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_modified_time
     *
     * @return the value of t_pec_capital.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_modified_time
     *
     * @param modifiedTime the value for t_pec_capital.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital.f_operater_name
     *
     * @return the value of t_pec_capital.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital.f_operater_name
     *
     * @param operaterName the value for t_pec_capital.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}