package com.parses.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class CapitalPricingEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_capital_no
     *
     * @mbg.generated
     */
    private String capitalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_capital_code
     *
     * @mbg.generated
     */
    private String capitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    private String pricingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    private String currentMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_match_type
     *
     * @mbg.generated
     */
    private Integer matchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_match_target_no
     *
     * @mbg.generated
     */
    private String matchTargetNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    private String repaymentFormulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    private String repaymentFormulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_year_rate
     *
     * @mbg.generated
     */
    private BigDecimal yearRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_month_rate
     *
     * @mbg.generated
     */
    private BigDecimal monthRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_day_rate
     *
     * @mbg.generated
     */
    private BigDecimal dayRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_clearing_formula_no
     *
     * @mbg.generated
     */
    private String clearingFormulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_clearing_formula_name
     *
     * @mbg.generated
     */
    private String clearingFormulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_profit_distribution_no
     *
     * @mbg.generated
     */
    private String profitDistributionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_profit_distribution_name
     *
     * @mbg.generated
     */
    private String profitDistributionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_remain_capital_code
     *
     * @mbg.generated
     */
    private String remainCapitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_remain_capital_name
     *
     * @mbg.generated
     */
    private String remainCapitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_remain_capital_member_no
     *
     * @mbg.generated
     */
    private String remainCapitalMemberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_compensatory_capital_code
     *
     * @mbg.generated
     */
    private String compensatoryCapitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_compensatory_capital_name
     *
     * @mbg.generated
     */
    private String compensatoryCapitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_compensatory_member_no
     *
     * @mbg.generated
     */
    private String compensatoryMemberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_compensatory_expand_info
     *
     * @mbg.generated
     */
    private String compensatoryExpandInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_capital_pricing.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_id
     *
     * @return the value of t_pec_capital_pricing.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_id
     *
     * @param id the value for t_pec_capital_pricing.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_version
     *
     * @return the value of t_pec_capital_pricing.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_version
     *
     * @param version the value for t_pec_capital_pricing.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_capital_no
     *
     * @return the value of t_pec_capital_pricing.f_capital_no
     *
     * @mbg.generated
     */
    public String getCapitalNo() {
        return capitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_capital_no
     *
     * @param capitalNo the value for t_pec_capital_pricing.f_capital_no
     *
     * @mbg.generated
     */
    public void setCapitalNo(String capitalNo) {
        this.capitalNo = capitalNo == null ? null : capitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_capital_code
     *
     * @return the value of t_pec_capital_pricing.f_capital_code
     *
     * @mbg.generated
     */
    public String getCapitalCode() {
        return capitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_capital_code
     *
     * @param capitalCode the value for t_pec_capital_pricing.f_capital_code
     *
     * @mbg.generated
     */
    public void setCapitalCode(String capitalCode) {
        this.capitalCode = capitalCode == null ? null : capitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_pricing_no
     *
     * @return the value of t_pec_capital_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    public String getPricingNo() {
        return pricingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_pricing_no
     *
     * @param pricingNo the value for t_pec_capital_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    public void setPricingNo(String pricingNo) {
        this.pricingNo = pricingNo == null ? null : pricingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_current_mirror_no
     *
     * @return the value of t_pec_capital_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    public String getCurrentMirrorNo() {
        return currentMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_current_mirror_no
     *
     * @param currentMirrorNo the value for t_pec_capital_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    public void setCurrentMirrorNo(String currentMirrorNo) {
        this.currentMirrorNo = currentMirrorNo == null ? null : currentMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_match_type
     *
     * @return the value of t_pec_capital_pricing.f_match_type
     *
     * @mbg.generated
     */
    public Integer getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_match_type
     *
     * @param matchType the value for t_pec_capital_pricing.f_match_type
     *
     * @mbg.generated
     */
    public void setMatchType(Integer matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_match_target_no
     *
     * @return the value of t_pec_capital_pricing.f_match_target_no
     *
     * @mbg.generated
     */
    public String getMatchTargetNo() {
        return matchTargetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_match_target_no
     *
     * @param matchTargetNo the value for t_pec_capital_pricing.f_match_target_no
     *
     * @mbg.generated
     */
    public void setMatchTargetNo(String matchTargetNo) {
        this.matchTargetNo = matchTargetNo == null ? null : matchTargetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_repayment_formula_no
     *
     * @return the value of t_pec_capital_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaNo() {
        return repaymentFormulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_repayment_formula_no
     *
     * @param repaymentFormulaNo the value for t_pec_capital_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaNo(String repaymentFormulaNo) {
        this.repaymentFormulaNo = repaymentFormulaNo == null ? null : repaymentFormulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_repayment_formula_name
     *
     * @return the value of t_pec_capital_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaName() {
        return repaymentFormulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_repayment_formula_name
     *
     * @param repaymentFormulaName the value for t_pec_capital_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaName(String repaymentFormulaName) {
        this.repaymentFormulaName = repaymentFormulaName == null ? null : repaymentFormulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_year_rate
     *
     * @return the value of t_pec_capital_pricing.f_year_rate
     *
     * @mbg.generated
     */
    public BigDecimal getYearRate() {
        return yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_year_rate
     *
     * @param yearRate the value for t_pec_capital_pricing.f_year_rate
     *
     * @mbg.generated
     */
    public void setYearRate(BigDecimal yearRate) {
        this.yearRate = yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_month_rate
     *
     * @return the value of t_pec_capital_pricing.f_month_rate
     *
     * @mbg.generated
     */
    public BigDecimal getMonthRate() {
        return monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_month_rate
     *
     * @param monthRate the value for t_pec_capital_pricing.f_month_rate
     *
     * @mbg.generated
     */
    public void setMonthRate(BigDecimal monthRate) {
        this.monthRate = monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_day_rate
     *
     * @return the value of t_pec_capital_pricing.f_day_rate
     *
     * @mbg.generated
     */
    public BigDecimal getDayRate() {
        return dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_day_rate
     *
     * @param dayRate the value for t_pec_capital_pricing.f_day_rate
     *
     * @mbg.generated
     */
    public void setDayRate(BigDecimal dayRate) {
        this.dayRate = dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_clearing_formula_no
     *
     * @return the value of t_pec_capital_pricing.f_clearing_formula_no
     *
     * @mbg.generated
     */
    public String getClearingFormulaNo() {
        return clearingFormulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_clearing_formula_no
     *
     * @param clearingFormulaNo the value for t_pec_capital_pricing.f_clearing_formula_no
     *
     * @mbg.generated
     */
    public void setClearingFormulaNo(String clearingFormulaNo) {
        this.clearingFormulaNo = clearingFormulaNo == null ? null : clearingFormulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_clearing_formula_name
     *
     * @return the value of t_pec_capital_pricing.f_clearing_formula_name
     *
     * @mbg.generated
     */
    public String getClearingFormulaName() {
        return clearingFormulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_clearing_formula_name
     *
     * @param clearingFormulaName the value for t_pec_capital_pricing.f_clearing_formula_name
     *
     * @mbg.generated
     */
    public void setClearingFormulaName(String clearingFormulaName) {
        this.clearingFormulaName = clearingFormulaName == null ? null : clearingFormulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_profit_distribution_no
     *
     * @return the value of t_pec_capital_pricing.f_profit_distribution_no
     *
     * @mbg.generated
     */
    public String getProfitDistributionNo() {
        return profitDistributionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_profit_distribution_no
     *
     * @param profitDistributionNo the value for t_pec_capital_pricing.f_profit_distribution_no
     *
     * @mbg.generated
     */
    public void setProfitDistributionNo(String profitDistributionNo) {
        this.profitDistributionNo = profitDistributionNo == null ? null : profitDistributionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_profit_distribution_name
     *
     * @return the value of t_pec_capital_pricing.f_profit_distribution_name
     *
     * @mbg.generated
     */
    public String getProfitDistributionName() {
        return profitDistributionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_profit_distribution_name
     *
     * @param profitDistributionName the value for t_pec_capital_pricing.f_profit_distribution_name
     *
     * @mbg.generated
     */
    public void setProfitDistributionName(String profitDistributionName) {
        this.profitDistributionName = profitDistributionName == null ? null : profitDistributionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_remain_capital_code
     *
     * @return the value of t_pec_capital_pricing.f_remain_capital_code
     *
     * @mbg.generated
     */
    public String getRemainCapitalCode() {
        return remainCapitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_remain_capital_code
     *
     * @param remainCapitalCode the value for t_pec_capital_pricing.f_remain_capital_code
     *
     * @mbg.generated
     */
    public void setRemainCapitalCode(String remainCapitalCode) {
        this.remainCapitalCode = remainCapitalCode == null ? null : remainCapitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_remain_capital_name
     *
     * @return the value of t_pec_capital_pricing.f_remain_capital_name
     *
     * @mbg.generated
     */
    public String getRemainCapitalName() {
        return remainCapitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_remain_capital_name
     *
     * @param remainCapitalName the value for t_pec_capital_pricing.f_remain_capital_name
     *
     * @mbg.generated
     */
    public void setRemainCapitalName(String remainCapitalName) {
        this.remainCapitalName = remainCapitalName == null ? null : remainCapitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_remain_capital_member_no
     *
     * @return the value of t_pec_capital_pricing.f_remain_capital_member_no
     *
     * @mbg.generated
     */
    public String getRemainCapitalMemberNo() {
        return remainCapitalMemberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_remain_capital_member_no
     *
     * @param remainCapitalMemberNo the value for t_pec_capital_pricing.f_remain_capital_member_no
     *
     * @mbg.generated
     */
    public void setRemainCapitalMemberNo(String remainCapitalMemberNo) {
        this.remainCapitalMemberNo = remainCapitalMemberNo == null ? null : remainCapitalMemberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_compensatory_capital_code
     *
     * @return the value of t_pec_capital_pricing.f_compensatory_capital_code
     *
     * @mbg.generated
     */
    public String getCompensatoryCapitalCode() {
        return compensatoryCapitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_compensatory_capital_code
     *
     * @param compensatoryCapitalCode the value for t_pec_capital_pricing.f_compensatory_capital_code
     *
     * @mbg.generated
     */
    public void setCompensatoryCapitalCode(String compensatoryCapitalCode) {
        this.compensatoryCapitalCode = compensatoryCapitalCode == null ? null : compensatoryCapitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_compensatory_capital_name
     *
     * @return the value of t_pec_capital_pricing.f_compensatory_capital_name
     *
     * @mbg.generated
     */
    public String getCompensatoryCapitalName() {
        return compensatoryCapitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_compensatory_capital_name
     *
     * @param compensatoryCapitalName the value for t_pec_capital_pricing.f_compensatory_capital_name
     *
     * @mbg.generated
     */
    public void setCompensatoryCapitalName(String compensatoryCapitalName) {
        this.compensatoryCapitalName = compensatoryCapitalName == null ? null : compensatoryCapitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_compensatory_member_no
     *
     * @return the value of t_pec_capital_pricing.f_compensatory_member_no
     *
     * @mbg.generated
     */
    public String getCompensatoryMemberNo() {
        return compensatoryMemberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_compensatory_member_no
     *
     * @param compensatoryMemberNo the value for t_pec_capital_pricing.f_compensatory_member_no
     *
     * @mbg.generated
     */
    public void setCompensatoryMemberNo(String compensatoryMemberNo) {
        this.compensatoryMemberNo = compensatoryMemberNo == null ? null : compensatoryMemberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_compensatory_expand_info
     *
     * @return the value of t_pec_capital_pricing.f_compensatory_expand_info
     *
     * @mbg.generated
     */
    public String getCompensatoryExpandInfo() {
        return compensatoryExpandInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_compensatory_expand_info
     *
     * @param compensatoryExpandInfo the value for t_pec_capital_pricing.f_compensatory_expand_info
     *
     * @mbg.generated
     */
    public void setCompensatoryExpandInfo(String compensatoryExpandInfo) {
        this.compensatoryExpandInfo = compensatoryExpandInfo == null ? null : compensatoryExpandInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_created_time
     *
     * @return the value of t_pec_capital_pricing.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_created_time
     *
     * @param createdTime the value for t_pec_capital_pricing.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_capital_pricing.f_modified_time
     *
     * @return the value of t_pec_capital_pricing.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_capital_pricing.f_modified_time
     *
     * @param modifiedTime the value for t_pec_capital_pricing.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}