package com.parses.dao.model;

import java.util.Date;

public class ElementDataEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_data_no
     *
     * @mbg.generated
     */
    private String dataNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_data_mirror_no
     *
     * @mbg.generated
     */
    private String dataMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_element_code
     *
     * @mbg.generated
     */
    private String elementCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_element_data
     *
     * @mbg.generated
     */
    private String elementData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_element_data.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_id
     *
     * @return the value of t_pec_element_data.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_id
     *
     * @param id the value for t_pec_element_data.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_version
     *
     * @return the value of t_pec_element_data.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_version
     *
     * @param version the value for t_pec_element_data.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_data_type
     *
     * @return the value of t_pec_element_data.f_data_type
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_data_type
     *
     * @param dataType the value for t_pec_element_data.f_data_type
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_data_no
     *
     * @return the value of t_pec_element_data.f_data_no
     *
     * @mbg.generated
     */
    public String getDataNo() {
        return dataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_data_no
     *
     * @param dataNo the value for t_pec_element_data.f_data_no
     *
     * @mbg.generated
     */
    public void setDataNo(String dataNo) {
        this.dataNo = dataNo == null ? null : dataNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_data_mirror_no
     *
     * @return the value of t_pec_element_data.f_data_mirror_no
     *
     * @mbg.generated
     */
    public String getDataMirrorNo() {
        return dataMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_data_mirror_no
     *
     * @param dataMirrorNo the value for t_pec_element_data.f_data_mirror_no
     *
     * @mbg.generated
     */
    public void setDataMirrorNo(String dataMirrorNo) {
        this.dataMirrorNo = dataMirrorNo == null ? null : dataMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_element_code
     *
     * @return the value of t_pec_element_data.f_element_code
     *
     * @mbg.generated
     */
    public String getElementCode() {
        return elementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_element_code
     *
     * @param elementCode the value for t_pec_element_data.f_element_code
     *
     * @mbg.generated
     */
    public void setElementCode(String elementCode) {
        this.elementCode = elementCode == null ? null : elementCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_element_data
     *
     * @return the value of t_pec_element_data.f_element_data
     *
     * @mbg.generated
     */
    public String getElementData() {
        return elementData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_element_data
     *
     * @param elementData the value for t_pec_element_data.f_element_data
     *
     * @mbg.generated
     */
    public void setElementData(String elementData) {
        this.elementData = elementData == null ? null : elementData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_created_time
     *
     * @return the value of t_pec_element_data.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_created_time
     *
     * @param createdTime the value for t_pec_element_data.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_element_data.f_modified_time
     *
     * @return the value of t_pec_element_data.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_element_data.f_modified_time
     *
     * @param modifiedTime the value for t_pec_element_data.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}