package com.parses.dao.model;

import java.util.Date;

public class FeeTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_version
     *
     * @mbg.generated
     */
    private Byte version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_template_no
     *
     * @mbg.generated
     */
    private String templateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_template_name
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_fee_code
     *
     * @mbg.generated
     */
    private String feeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_fee_name
     *
     * @mbg.generated
     */
    private String feeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_formula_no
     *
     * @mbg.generated
     */
    private String formulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_formula_name
     *
     * @mbg.generated
     */
    private String formulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_fee_template.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_id
     *
     * @return the value of t_pec_fee_template.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_id
     *
     * @param id the value for t_pec_fee_template.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_version
     *
     * @return the value of t_pec_fee_template.f_version
     *
     * @mbg.generated
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_version
     *
     * @param version the value for t_pec_fee_template.f_version
     *
     * @mbg.generated
     */
    public void setVersion(Byte version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_template_no
     *
     * @return the value of t_pec_fee_template.f_template_no
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_template_no
     *
     * @param templateNo the value for t_pec_fee_template.f_template_no
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_template_name
     *
     * @return the value of t_pec_fee_template.f_template_name
     *
     * @mbg.generated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_template_name
     *
     * @param templateName the value for t_pec_fee_template.f_template_name
     *
     * @mbg.generated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_fee_code
     *
     * @return the value of t_pec_fee_template.f_fee_code
     *
     * @mbg.generated
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_fee_code
     *
     * @param feeCode the value for t_pec_fee_template.f_fee_code
     *
     * @mbg.generated
     */
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode == null ? null : feeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_fee_name
     *
     * @return the value of t_pec_fee_template.f_fee_name
     *
     * @mbg.generated
     */
    public String getFeeName() {
        return feeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_fee_name
     *
     * @param feeName the value for t_pec_fee_template.f_fee_name
     *
     * @mbg.generated
     */
    public void setFeeName(String feeName) {
        this.feeName = feeName == null ? null : feeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_formula_no
     *
     * @return the value of t_pec_fee_template.f_formula_no
     *
     * @mbg.generated
     */
    public String getFormulaNo() {
        return formulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_formula_no
     *
     * @param formulaNo the value for t_pec_fee_template.f_formula_no
     *
     * @mbg.generated
     */
    public void setFormulaNo(String formulaNo) {
        this.formulaNo = formulaNo == null ? null : formulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_formula_name
     *
     * @return the value of t_pec_fee_template.f_formula_name
     *
     * @mbg.generated
     */
    public String getFormulaName() {
        return formulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_formula_name
     *
     * @param formulaName the value for t_pec_fee_template.f_formula_name
     *
     * @mbg.generated
     */
    public void setFormulaName(String formulaName) {
        this.formulaName = formulaName == null ? null : formulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_created_time
     *
     * @return the value of t_pec_fee_template.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_created_time
     *
     * @param createdTime the value for t_pec_fee_template.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_modified_time
     *
     * @return the value of t_pec_fee_template.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_modified_time
     *
     * @param modifiedTime the value for t_pec_fee_template.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_fee_template.f_operater_name
     *
     * @return the value of t_pec_fee_template.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_fee_template.f_operater_name
     *
     * @param operaterName the value for t_pec_fee_template.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}