package com.parses.dao.model;

import java.util.Date;

public class PricingFeeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_pricing_type
     *
     * @mbg.generated
     */
    private Integer pricingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_pricing_no
     *
     * @mbg.generated
     */
    private String pricingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_pricing_mirror_no
     *
     * @mbg.generated
     */
    private String pricingMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_fee_code
     *
     * @mbg.generated
     */
    private String feeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_fee_name
     *
     * @mbg.generated
     */
    private String feeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_fee_description
     *
     * @mbg.generated
     */
    private String feeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_calc_period
     *
     * @mbg.generated
     */
    private Integer calcPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_type
     *
     * @mbg.generated
     */
    private Integer formulaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_no
     *
     * @mbg.generated
     */
    private String formulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_name
     *
     * @mbg.generated
     */
    private String formulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_params_json
     *
     * @mbg.generated
     */
    private String formulaParamsJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_description
     *
     * @mbg.generated
     */
    private String formulaDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_carbon_name
     *
     * @mbg.generated
     */
    private String formulaCarbonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_carbon_no
     *
     * @mbg.generated
     */
    private String formulaCarbonNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_formula_carbon_description
     *
     * @mbg.generated
     */
    private String formulaCarbonDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_pricing_fee.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_id
     *
     * @return the value of t_pec_pricing_fee.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_id
     *
     * @param id the value for t_pec_pricing_fee.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_version
     *
     * @return the value of t_pec_pricing_fee.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_version
     *
     * @param version the value for t_pec_pricing_fee.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_pricing_type
     *
     * @return the value of t_pec_pricing_fee.f_pricing_type
     *
     * @mbg.generated
     */
    public Integer getPricingType() {
        return pricingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_pricing_type
     *
     * @param pricingType the value for t_pec_pricing_fee.f_pricing_type
     *
     * @mbg.generated
     */
    public void setPricingType(Integer pricingType) {
        this.pricingType = pricingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_pricing_no
     *
     * @return the value of t_pec_pricing_fee.f_pricing_no
     *
     * @mbg.generated
     */
    public String getPricingNo() {
        return pricingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_pricing_no
     *
     * @param pricingNo the value for t_pec_pricing_fee.f_pricing_no
     *
     * @mbg.generated
     */
    public void setPricingNo(String pricingNo) {
        this.pricingNo = pricingNo == null ? null : pricingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_pricing_mirror_no
     *
     * @return the value of t_pec_pricing_fee.f_pricing_mirror_no
     *
     * @mbg.generated
     */
    public String getPricingMirrorNo() {
        return pricingMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_pricing_mirror_no
     *
     * @param pricingMirrorNo the value for t_pec_pricing_fee.f_pricing_mirror_no
     *
     * @mbg.generated
     */
    public void setPricingMirrorNo(String pricingMirrorNo) {
        this.pricingMirrorNo = pricingMirrorNo == null ? null : pricingMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_fee_code
     *
     * @return the value of t_pec_pricing_fee.f_fee_code
     *
     * @mbg.generated
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_fee_code
     *
     * @param feeCode the value for t_pec_pricing_fee.f_fee_code
     *
     * @mbg.generated
     */
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode == null ? null : feeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_fee_name
     *
     * @return the value of t_pec_pricing_fee.f_fee_name
     *
     * @mbg.generated
     */
    public String getFeeName() {
        return feeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_fee_name
     *
     * @param feeName the value for t_pec_pricing_fee.f_fee_name
     *
     * @mbg.generated
     */
    public void setFeeName(String feeName) {
        this.feeName = feeName == null ? null : feeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_fee_description
     *
     * @return the value of t_pec_pricing_fee.f_fee_description
     *
     * @mbg.generated
     */
    public String getFeeDescription() {
        return feeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_fee_description
     *
     * @param feeDescription the value for t_pec_pricing_fee.f_fee_description
     *
     * @mbg.generated
     */
    public void setFeeDescription(String feeDescription) {
        this.feeDescription = feeDescription == null ? null : feeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_calc_period
     *
     * @return the value of t_pec_pricing_fee.f_calc_period
     *
     * @mbg.generated
     */
    public Integer getCalcPeriod() {
        return calcPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_calc_period
     *
     * @param calcPeriod the value for t_pec_pricing_fee.f_calc_period
     *
     * @mbg.generated
     */
    public void setCalcPeriod(Integer calcPeriod) {
        this.calcPeriod = calcPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_type
     *
     * @return the value of t_pec_pricing_fee.f_formula_type
     *
     * @mbg.generated
     */
    public Integer getFormulaType() {
        return formulaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_type
     *
     * @param formulaType the value for t_pec_pricing_fee.f_formula_type
     *
     * @mbg.generated
     */
    public void setFormulaType(Integer formulaType) {
        this.formulaType = formulaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_no
     *
     * @return the value of t_pec_pricing_fee.f_formula_no
     *
     * @mbg.generated
     */
    public String getFormulaNo() {
        return formulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_no
     *
     * @param formulaNo the value for t_pec_pricing_fee.f_formula_no
     *
     * @mbg.generated
     */
    public void setFormulaNo(String formulaNo) {
        this.formulaNo = formulaNo == null ? null : formulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_name
     *
     * @return the value of t_pec_pricing_fee.f_formula_name
     *
     * @mbg.generated
     */
    public String getFormulaName() {
        return formulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_name
     *
     * @param formulaName the value for t_pec_pricing_fee.f_formula_name
     *
     * @mbg.generated
     */
    public void setFormulaName(String formulaName) {
        this.formulaName = formulaName == null ? null : formulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_params_json
     *
     * @return the value of t_pec_pricing_fee.f_formula_params_json
     *
     * @mbg.generated
     */
    public String getFormulaParamsJson() {
        return formulaParamsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_params_json
     *
     * @param formulaParamsJson the value for t_pec_pricing_fee.f_formula_params_json
     *
     * @mbg.generated
     */
    public void setFormulaParamsJson(String formulaParamsJson) {
        this.formulaParamsJson = formulaParamsJson == null ? null : formulaParamsJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_created_time
     *
     * @return the value of t_pec_pricing_fee.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_created_time
     *
     * @param createdTime the value for t_pec_pricing_fee.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_modified_time
     *
     * @return the value of t_pec_pricing_fee.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_modified_time
     *
     * @param modifiedTime the value for t_pec_pricing_fee.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_description
     *
     * @return the value of t_pec_pricing_fee.f_formula_description
     *
     * @mbg.generated
     */
    public String getFormulaDescription() {
        return formulaDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_description
     *
     * @param formulaDescription the value for t_pec_pricing_fee.f_formula_description
     *
     * @mbg.generated
     */
    public void setFormulaDescription(String formulaDescription) {
        this.formulaDescription = formulaDescription == null ? null : formulaDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_carbon_name
     *
     * @return the value of t_pec_pricing_fee.f_formula_carbon_name
     *
     * @mbg.generated
     */
    public String getFormulaCarbonName() {
        return formulaCarbonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_carbon_name
     *
     * @param formulaCarbonName the value for t_pec_pricing_fee.f_formula_carbon_name
     *
     * @mbg.generated
     */
    public void setFormulaCarbonName(String formulaCarbonName) {
        this.formulaCarbonName = formulaCarbonName == null ? null : formulaCarbonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_carbon_no
     *
     * @return the value of t_pec_pricing_fee.f_formula_carbon_no
     *
     * @mbg.generated
     */
    public String getFormulaCarbonNo() {
        return formulaCarbonNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_carbon_no
     *
     * @param formulaCarbonNo the value for t_pec_pricing_fee.f_formula_carbon_no
     *
     * @mbg.generated
     */
    public void setFormulaCarbonNo(String formulaCarbonNo) {
        this.formulaCarbonNo = formulaCarbonNo == null ? null : formulaCarbonNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_formula_carbon_description
     *
     * @return the value of t_pec_pricing_fee.f_formula_carbon_description
     *
     * @mbg.generated
     */
    public String getFormulaCarbonDescription() {
        return formulaCarbonDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_formula_carbon_description
     *
     * @param formulaCarbonDescription the value for t_pec_pricing_fee.f_formula_carbon_description
     *
     * @mbg.generated
     */
    public void setFormulaCarbonDescription(String formulaCarbonDescription) {
        this.formulaCarbonDescription = formulaCarbonDescription == null ? null : formulaCarbonDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_pricing_fee.f_operater_name
     *
     * @return the value of t_pec_pricing_fee.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_pricing_fee.f_operater_name
     *
     * @param operaterName the value for t_pec_pricing_fee.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}