package com.parses.dao.model;

import java.util.Date;

public class ProductEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_current_mirror_no
     *
     * @mbg.generated
     */
    private String currentMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_template_no
     *
     * @mbg.generated
     */
    private String templateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_template_mirror_no
     *
     * @mbg.generated
     */
    private String templateMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_loan_type
     *
     * @mbg.generated
     */
    private String loanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_business_group_code
     *
     * @mbg.generated
     */
    private String businessGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_channel_code
     *
     * @mbg.generated
     */
    private String productChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_start_datetime
     *
     * @mbg.generated
     */
    private Date productStartDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_end_datetime
     *
     * @mbg.generated
     */
    private Date productEndDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_product_status
     *
     * @mbg.generated
     */
    private String productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_id
     *
     * @return the value of t_pec_product.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_id
     *
     * @param id the value for t_pec_product.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_version
     *
     * @return the value of t_pec_product.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_version
     *
     * @param version the value for t_pec_product.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_no
     *
     * @return the value of t_pec_product.f_product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_no
     *
     * @param productNo the value for t_pec_product.f_product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_current_mirror_no
     *
     * @return the value of t_pec_product.f_current_mirror_no
     *
     * @mbg.generated
     */
    public String getCurrentMirrorNo() {
        return currentMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_current_mirror_no
     *
     * @param currentMirrorNo the value for t_pec_product.f_current_mirror_no
     *
     * @mbg.generated
     */
    public void setCurrentMirrorNo(String currentMirrorNo) {
        this.currentMirrorNo = currentMirrorNo == null ? null : currentMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_template_no
     *
     * @return the value of t_pec_product.f_template_no
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_template_no
     *
     * @param templateNo the value for t_pec_product.f_template_no
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_template_mirror_no
     *
     * @return the value of t_pec_product.f_template_mirror_no
     *
     * @mbg.generated
     */
    public String getTemplateMirrorNo() {
        return templateMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_template_mirror_no
     *
     * @param templateMirrorNo the value for t_pec_product.f_template_mirror_no
     *
     * @mbg.generated
     */
    public void setTemplateMirrorNo(String templateMirrorNo) {
        this.templateMirrorNo = templateMirrorNo == null ? null : templateMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_loan_type
     *
     * @return the value of t_pec_product.f_loan_type
     *
     * @mbg.generated
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_loan_type
     *
     * @param loanType the value for t_pec_product.f_loan_type
     *
     * @mbg.generated
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_code
     *
     * @return the value of t_pec_product.f_product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_code
     *
     * @param productCode the value for t_pec_product.f_product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_name
     *
     * @return the value of t_pec_product.f_product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_name
     *
     * @param productName the value for t_pec_product.f_product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_business_group_code
     *
     * @return the value of t_pec_product.f_business_group_code
     *
     * @mbg.generated
     */
    public String getBusinessGroupCode() {
        return businessGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_business_group_code
     *
     * @param businessGroupCode the value for t_pec_product.f_business_group_code
     *
     * @mbg.generated
     */
    public void setBusinessGroupCode(String businessGroupCode) {
        this.businessGroupCode = businessGroupCode == null ? null : businessGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_channel_code
     *
     * @return the value of t_pec_product.f_product_channel_code
     *
     * @mbg.generated
     */
    public String getProductChannelCode() {
        return productChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_channel_code
     *
     * @param productChannelCode the value for t_pec_product.f_product_channel_code
     *
     * @mbg.generated
     */
    public void setProductChannelCode(String productChannelCode) {
        this.productChannelCode = productChannelCode == null ? null : productChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_start_datetime
     *
     * @return the value of t_pec_product.f_product_start_datetime
     *
     * @mbg.generated
     */
    public Date getProductStartDatetime() {
        return productStartDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_start_datetime
     *
     * @param productStartDatetime the value for t_pec_product.f_product_start_datetime
     *
     * @mbg.generated
     */
    public void setProductStartDatetime(Date productStartDatetime) {
        this.productStartDatetime = productStartDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_end_datetime
     *
     * @return the value of t_pec_product.f_product_end_datetime
     *
     * @mbg.generated
     */
    public Date getProductEndDatetime() {
        return productEndDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_end_datetime
     *
     * @param productEndDatetime the value for t_pec_product.f_product_end_datetime
     *
     * @mbg.generated
     */
    public void setProductEndDatetime(Date productEndDatetime) {
        this.productEndDatetime = productEndDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_product_status
     *
     * @return the value of t_pec_product.f_product_status
     *
     * @mbg.generated
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_product_status
     *
     * @param productStatus the value for t_pec_product.f_product_status
     *
     * @mbg.generated
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_created_time
     *
     * @return the value of t_pec_product.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_created_time
     *
     * @param createdTime the value for t_pec_product.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_modified_time
     *
     * @return the value of t_pec_product.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_modified_time
     *
     * @param modifiedTime the value for t_pec_product.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product.f_operater_name
     *
     * @return the value of t_pec_product.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product.f_operater_name
     *
     * @param operaterName the value for t_pec_product.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}