package com.parses.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductPricingEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_product_price_status
     *
     * @mbg.generated
     */
    private String productPriceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    private String pricingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    private String currentMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_total_stage
     *
     * @mbg.generated
     */
    private Integer totalStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_rank_level
     *
     * @mbg.generated
     */
    private String rankLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_min_rank
     *
     * @mbg.generated
     */
    private Integer minRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_max_rank
     *
     * @mbg.generated
     */
    private Integer maxRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    private String repaymentFormulaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    private String repaymentFormulaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_year_rate
     *
     * @mbg.generated
     */
    private BigDecimal yearRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_month_rate
     *
     * @mbg.generated
     */
    private BigDecimal monthRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_day_rate
     *
     * @mbg.generated
     */
    private BigDecimal dayRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_rate_flag
     *
     * @mbg.generated
     */
    private String rateFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_annualized_rate
     *
     * @mbg.generated
     */
    private BigDecimal annualizedRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_service_annualized_rate
     *
     * @mbg.generated
     */
    private BigDecimal serviceAnnualizedRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_apr_year_rate
     *
     * @mbg.generated
     */
    private BigDecimal aprYearRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_apr_month_rate
     *
     * @mbg.generated
     */
    private BigDecimal aprMonthRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_apr_day_rate
     *
     * @mbg.generated
     */
    private BigDecimal aprDayRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_capital_code
     *
     * @mbg.generated
     */
    private String capitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_consumer_label
     *
     * @mbg.generated
     */
    private String consumerLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_repayment_way
     *
     * @mbg.generated
     */
    private String repaymentWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_channel_type
     *
     * @mbg.generated
     */
    private String channelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_activity_code
     *
     * @mbg.generated
     */
    private String activityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_product_pricing.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_id
     *
     * @return the value of t_pec_product_pricing.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_id
     *
     * @param id the value for t_pec_product_pricing.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_version
     *
     * @return the value of t_pec_product_pricing.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_version
     *
     * @param version the value for t_pec_product_pricing.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_product_price_status
     *
     * @return the value of t_pec_product_pricing.f_product_price_status
     *
     * @mbg.generated
     */
    public String getProductPriceStatus() {
        return productPriceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_product_price_status
     *
     * @param productPriceStatus the value for t_pec_product_pricing.f_product_price_status
     *
     * @mbg.generated
     */
    public void setProductPriceStatus(String productPriceStatus) {
        this.productPriceStatus = productPriceStatus == null ? null : productPriceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_product_no
     *
     * @return the value of t_pec_product_pricing.f_product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_product_no
     *
     * @param productNo the value for t_pec_product_pricing.f_product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_product_code
     *
     * @return the value of t_pec_product_pricing.f_product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_product_code
     *
     * @param productCode the value for t_pec_product_pricing.f_product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_pricing_no
     *
     * @return the value of t_pec_product_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    public String getPricingNo() {
        return pricingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_pricing_no
     *
     * @param pricingNo the value for t_pec_product_pricing.f_pricing_no
     *
     * @mbg.generated
     */
    public void setPricingNo(String pricingNo) {
        this.pricingNo = pricingNo == null ? null : pricingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_current_mirror_no
     *
     * @return the value of t_pec_product_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    public String getCurrentMirrorNo() {
        return currentMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_current_mirror_no
     *
     * @param currentMirrorNo the value for t_pec_product_pricing.f_current_mirror_no
     *
     * @mbg.generated
     */
    public void setCurrentMirrorNo(String currentMirrorNo) {
        this.currentMirrorNo = currentMirrorNo == null ? null : currentMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_total_stage
     *
     * @return the value of t_pec_product_pricing.f_total_stage
     *
     * @mbg.generated
     */
    public Integer getTotalStage() {
        return totalStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_total_stage
     *
     * @param totalStage the value for t_pec_product_pricing.f_total_stage
     *
     * @mbg.generated
     */
    public void setTotalStage(Integer totalStage) {
        this.totalStage = totalStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_rank_level
     *
     * @return the value of t_pec_product_pricing.f_rank_level
     *
     * @mbg.generated
     */
    public String getRankLevel() {
        return rankLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_rank_level
     *
     * @param rankLevel the value for t_pec_product_pricing.f_rank_level
     *
     * @mbg.generated
     */
    public void setRankLevel(String rankLevel) {
        this.rankLevel = rankLevel == null ? null : rankLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_min_rank
     *
     * @return the value of t_pec_product_pricing.f_min_rank
     *
     * @mbg.generated
     */
    public Integer getMinRank() {
        return minRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_min_rank
     *
     * @param minRank the value for t_pec_product_pricing.f_min_rank
     *
     * @mbg.generated
     */
    public void setMinRank(Integer minRank) {
        this.minRank = minRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_max_rank
     *
     * @return the value of t_pec_product_pricing.f_max_rank
     *
     * @mbg.generated
     */
    public Integer getMaxRank() {
        return maxRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_max_rank
     *
     * @param maxRank the value for t_pec_product_pricing.f_max_rank
     *
     * @mbg.generated
     */
    public void setMaxRank(Integer maxRank) {
        this.maxRank = maxRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_repayment_formula_no
     *
     * @return the value of t_pec_product_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaNo() {
        return repaymentFormulaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_repayment_formula_no
     *
     * @param repaymentFormulaNo the value for t_pec_product_pricing.f_repayment_formula_no
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaNo(String repaymentFormulaNo) {
        this.repaymentFormulaNo = repaymentFormulaNo == null ? null : repaymentFormulaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_repayment_formula_name
     *
     * @return the value of t_pec_product_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public String getRepaymentFormulaName() {
        return repaymentFormulaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_repayment_formula_name
     *
     * @param repaymentFormulaName the value for t_pec_product_pricing.f_repayment_formula_name
     *
     * @mbg.generated
     */
    public void setRepaymentFormulaName(String repaymentFormulaName) {
        this.repaymentFormulaName = repaymentFormulaName == null ? null : repaymentFormulaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_year_rate
     *
     * @return the value of t_pec_product_pricing.f_year_rate
     *
     * @mbg.generated
     */
    public BigDecimal getYearRate() {
        return yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_year_rate
     *
     * @param yearRate the value for t_pec_product_pricing.f_year_rate
     *
     * @mbg.generated
     */
    public void setYearRate(BigDecimal yearRate) {
        this.yearRate = yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_month_rate
     *
     * @return the value of t_pec_product_pricing.f_month_rate
     *
     * @mbg.generated
     */
    public BigDecimal getMonthRate() {
        return monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_month_rate
     *
     * @param monthRate the value for t_pec_product_pricing.f_month_rate
     *
     * @mbg.generated
     */
    public void setMonthRate(BigDecimal monthRate) {
        this.monthRate = monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_day_rate
     *
     * @return the value of t_pec_product_pricing.f_day_rate
     *
     * @mbg.generated
     */
    public BigDecimal getDayRate() {
        return dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_day_rate
     *
     * @param dayRate the value for t_pec_product_pricing.f_day_rate
     *
     * @mbg.generated
     */
    public void setDayRate(BigDecimal dayRate) {
        this.dayRate = dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_rate_flag
     *
     * @return the value of t_pec_product_pricing.f_rate_flag
     *
     * @mbg.generated
     */
    public String getRateFlag() {
        return rateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_rate_flag
     *
     * @param rateFlag the value for t_pec_product_pricing.f_rate_flag
     *
     * @mbg.generated
     */
    public void setRateFlag(String rateFlag) {
        this.rateFlag = rateFlag == null ? null : rateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_annualized_rate
     *
     * @return the value of t_pec_product_pricing.f_annualized_rate
     *
     * @mbg.generated
     */
    public BigDecimal getAnnualizedRate() {
        return annualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_annualized_rate
     *
     * @param annualizedRate the value for t_pec_product_pricing.f_annualized_rate
     *
     * @mbg.generated
     */
    public void setAnnualizedRate(BigDecimal annualizedRate) {
        this.annualizedRate = annualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_service_annualized_rate
     *
     * @return the value of t_pec_product_pricing.f_service_annualized_rate
     *
     * @mbg.generated
     */
    public BigDecimal getServiceAnnualizedRate() {
        return serviceAnnualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_service_annualized_rate
     *
     * @param serviceAnnualizedRate the value for t_pec_product_pricing.f_service_annualized_rate
     *
     * @mbg.generated
     */
    public void setServiceAnnualizedRate(BigDecimal serviceAnnualizedRate) {
        this.serviceAnnualizedRate = serviceAnnualizedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_apr_year_rate
     *
     * @return the value of t_pec_product_pricing.f_apr_year_rate
     *
     * @mbg.generated
     */
    public BigDecimal getAprYearRate() {
        return aprYearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_apr_year_rate
     *
     * @param aprYearRate the value for t_pec_product_pricing.f_apr_year_rate
     *
     * @mbg.generated
     */
    public void setAprYearRate(BigDecimal aprYearRate) {
        this.aprYearRate = aprYearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_apr_month_rate
     *
     * @return the value of t_pec_product_pricing.f_apr_month_rate
     *
     * @mbg.generated
     */
    public BigDecimal getAprMonthRate() {
        return aprMonthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_apr_month_rate
     *
     * @param aprMonthRate the value for t_pec_product_pricing.f_apr_month_rate
     *
     * @mbg.generated
     */
    public void setAprMonthRate(BigDecimal aprMonthRate) {
        this.aprMonthRate = aprMonthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_apr_day_rate
     *
     * @return the value of t_pec_product_pricing.f_apr_day_rate
     *
     * @mbg.generated
     */
    public BigDecimal getAprDayRate() {
        return aprDayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_apr_day_rate
     *
     * @param aprDayRate the value for t_pec_product_pricing.f_apr_day_rate
     *
     * @mbg.generated
     */
    public void setAprDayRate(BigDecimal aprDayRate) {
        this.aprDayRate = aprDayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_capital_code
     *
     * @return the value of t_pec_product_pricing.f_capital_code
     *
     * @mbg.generated
     */
    public String getCapitalCode() {
        return capitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_capital_code
     *
     * @param capitalCode the value for t_pec_product_pricing.f_capital_code
     *
     * @mbg.generated
     */
    public void setCapitalCode(String capitalCode) {
        this.capitalCode = capitalCode == null ? null : capitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_consumer_label
     *
     * @return the value of t_pec_product_pricing.f_consumer_label
     *
     * @mbg.generated
     */
    public String getConsumerLabel() {
        return consumerLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_consumer_label
     *
     * @param consumerLabel the value for t_pec_product_pricing.f_consumer_label
     *
     * @mbg.generated
     */
    public void setConsumerLabel(String consumerLabel) {
        this.consumerLabel = consumerLabel == null ? null : consumerLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_repayment_way
     *
     * @return the value of t_pec_product_pricing.f_repayment_way
     *
     * @mbg.generated
     */
    public String getRepaymentWay() {
        return repaymentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_repayment_way
     *
     * @param repaymentWay the value for t_pec_product_pricing.f_repayment_way
     *
     * @mbg.generated
     */
    public void setRepaymentWay(String repaymentWay) {
        this.repaymentWay = repaymentWay == null ? null : repaymentWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_channel_type
     *
     * @return the value of t_pec_product_pricing.f_channel_type
     *
     * @mbg.generated
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_channel_type
     *
     * @param channelType the value for t_pec_product_pricing.f_channel_type
     *
     * @mbg.generated
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_activity_code
     *
     * @return the value of t_pec_product_pricing.f_activity_code
     *
     * @mbg.generated
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_activity_code
     *
     * @param activityCode the value for t_pec_product_pricing.f_activity_code
     *
     * @mbg.generated
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_remark
     *
     * @return the value of t_pec_product_pricing.f_remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_remark
     *
     * @param remark the value for t_pec_product_pricing.f_remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_operator_name
     *
     * @return the value of t_pec_product_pricing.f_operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_operator_name
     *
     * @param operatorName the value for t_pec_product_pricing.f_operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_created_time
     *
     * @return the value of t_pec_product_pricing.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_created_time
     *
     * @param createdTime the value for t_pec_product_pricing.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_product_pricing.f_modified_time
     *
     * @return the value of t_pec_product_pricing.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_product_pricing.f_modified_time
     *
     * @param modifiedTime the value for t_pec_product_pricing.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}