package com.parses.dao.model;

import java.util.Date;

public class TemplateElementEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_template_mirror_no
     *
     * @mbg.generated
     */
    private String templateMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_source_type
     *
     * @mbg.generated
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_element_type
     *
     * @mbg.generated
     */
    private String elementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_element_code
     *
     * @mbg.generated
     */
    private String elementCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_element_name
     *
     * @mbg.generated
     */
    private String elementName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_element_description
     *
     * @mbg.generated
     */
    private String elementDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_input_type
     *
     * @mbg.generated
     */
    private String inputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_default_value
     *
     * @mbg.generated
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_suggest_value_type
     *
     * @mbg.generated
     */
    private String suggestValueType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_local_suggest_value_json
     *
     * @mbg.generated
     */
    private String localSuggestValueJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_is_required
     *
     * @mbg.generated
     */
    private String isRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_display_rule
     *
     * @mbg.generated
     */
    private String displayRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_valid_rule
     *
     * @mbg.generated
     */
    private String validRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_valid_tips
     *
     * @mbg.generated
     */
    private String validTips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template_element.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_id
     *
     * @return the value of t_pec_template_element.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_id
     *
     * @param id the value for t_pec_template_element.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_version
     *
     * @return the value of t_pec_template_element.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_version
     *
     * @param version the value for t_pec_template_element.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_template_mirror_no
     *
     * @return the value of t_pec_template_element.f_template_mirror_no
     *
     * @mbg.generated
     */
    public String getTemplateMirrorNo() {
        return templateMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_template_mirror_no
     *
     * @param templateMirrorNo the value for t_pec_template_element.f_template_mirror_no
     *
     * @mbg.generated
     */
    public void setTemplateMirrorNo(String templateMirrorNo) {
        this.templateMirrorNo = templateMirrorNo == null ? null : templateMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_source_type
     *
     * @return the value of t_pec_template_element.f_source_type
     *
     * @mbg.generated
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_source_type
     *
     * @param sourceType the value for t_pec_template_element.f_source_type
     *
     * @mbg.generated
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_element_type
     *
     * @return the value of t_pec_template_element.f_element_type
     *
     * @mbg.generated
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_element_type
     *
     * @param elementType the value for t_pec_template_element.f_element_type
     *
     * @mbg.generated
     */
    public void setElementType(String elementType) {
        this.elementType = elementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_element_code
     *
     * @return the value of t_pec_template_element.f_element_code
     *
     * @mbg.generated
     */
    public String getElementCode() {
        return elementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_element_code
     *
     * @param elementCode the value for t_pec_template_element.f_element_code
     *
     * @mbg.generated
     */
    public void setElementCode(String elementCode) {
        this.elementCode = elementCode == null ? null : elementCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_element_name
     *
     * @return the value of t_pec_template_element.f_element_name
     *
     * @mbg.generated
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_element_name
     *
     * @param elementName the value for t_pec_template_element.f_element_name
     *
     * @mbg.generated
     */
    public void setElementName(String elementName) {
        this.elementName = elementName == null ? null : elementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_element_description
     *
     * @return the value of t_pec_template_element.f_element_description
     *
     * @mbg.generated
     */
    public String getElementDescription() {
        return elementDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_element_description
     *
     * @param elementDescription the value for t_pec_template_element.f_element_description
     *
     * @mbg.generated
     */
    public void setElementDescription(String elementDescription) {
        this.elementDescription = elementDescription == null ? null : elementDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_input_type
     *
     * @return the value of t_pec_template_element.f_input_type
     *
     * @mbg.generated
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_input_type
     *
     * @param inputType the value for t_pec_template_element.f_input_type
     *
     * @mbg.generated
     */
    public void setInputType(String inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_default_value
     *
     * @return the value of t_pec_template_element.f_default_value
     *
     * @mbg.generated
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_default_value
     *
     * @param defaultValue the value for t_pec_template_element.f_default_value
     *
     * @mbg.generated
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_suggest_value_type
     *
     * @return the value of t_pec_template_element.f_suggest_value_type
     *
     * @mbg.generated
     */
    public String getSuggestValueType() {
        return suggestValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_suggest_value_type
     *
     * @param suggestValueType the value for t_pec_template_element.f_suggest_value_type
     *
     * @mbg.generated
     */
    public void setSuggestValueType(String suggestValueType) {
        this.suggestValueType = suggestValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_local_suggest_value_json
     *
     * @return the value of t_pec_template_element.f_local_suggest_value_json
     *
     * @mbg.generated
     */
    public String getLocalSuggestValueJson() {
        return localSuggestValueJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_local_suggest_value_json
     *
     * @param localSuggestValueJson the value for t_pec_template_element.f_local_suggest_value_json
     *
     * @mbg.generated
     */
    public void setLocalSuggestValueJson(String localSuggestValueJson) {
        this.localSuggestValueJson = localSuggestValueJson == null ? null : localSuggestValueJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_is_required
     *
     * @return the value of t_pec_template_element.f_is_required
     *
     * @mbg.generated
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_is_required
     *
     * @param isRequired the value for t_pec_template_element.f_is_required
     *
     * @mbg.generated
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_display_rule
     *
     * @return the value of t_pec_template_element.f_display_rule
     *
     * @mbg.generated
     */
    public String getDisplayRule() {
        return displayRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_display_rule
     *
     * @param displayRule the value for t_pec_template_element.f_display_rule
     *
     * @mbg.generated
     */
    public void setDisplayRule(String displayRule) {
        this.displayRule = displayRule == null ? null : displayRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_valid_rule
     *
     * @return the value of t_pec_template_element.f_valid_rule
     *
     * @mbg.generated
     */
    public String getValidRule() {
        return validRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_valid_rule
     *
     * @param validRule the value for t_pec_template_element.f_valid_rule
     *
     * @mbg.generated
     */
    public void setValidRule(String validRule) {
        this.validRule = validRule == null ? null : validRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_valid_tips
     *
     * @return the value of t_pec_template_element.f_valid_tips
     *
     * @mbg.generated
     */
    public String getValidTips() {
        return validTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_valid_tips
     *
     * @param validTips the value for t_pec_template_element.f_valid_tips
     *
     * @mbg.generated
     */
    public void setValidTips(String validTips) {
        this.validTips = validTips == null ? null : validTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_sort_order
     *
     * @return the value of t_pec_template_element.f_sort_order
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_sort_order
     *
     * @param sortOrder the value for t_pec_template_element.f_sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_created_time
     *
     * @return the value of t_pec_template_element.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_created_time
     *
     * @param createdTime the value for t_pec_template_element.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template_element.f_modified_time
     *
     * @return the value of t_pec_template_element.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template_element.f_modified_time
     *
     * @param modifiedTime the value for t_pec_template_element.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}