package com.parses.dao.model;

import java.util.Date;

public class TemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_source_type
     *
     * @mbg.generated
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_template_status
     *
     * @mbg.generated
     */
    private String templateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_template_no
     *
     * @mbg.generated
     */
    private String templateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_current_mirror_no
     *
     * @mbg.generated
     */
    private String currentMirrorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_template_name
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_template_description
     *
     * @mbg.generated
     */
    private String templateDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pec_template.f_operater_name
     *
     * @mbg.generated
     */
    private String operaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_id
     *
     * @return the value of t_pec_template.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_id
     *
     * @param id the value for t_pec_template.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_version
     *
     * @return the value of t_pec_template.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_version
     *
     * @param version the value for t_pec_template.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_source_type
     *
     * @return the value of t_pec_template.f_source_type
     *
     * @mbg.generated
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_source_type
     *
     * @param sourceType the value for t_pec_template.f_source_type
     *
     * @mbg.generated
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_template_status
     *
     * @return the value of t_pec_template.f_template_status
     *
     * @mbg.generated
     */
    public String getTemplateStatus() {
        return templateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_template_status
     *
     * @param templateStatus the value for t_pec_template.f_template_status
     *
     * @mbg.generated
     */
    public void setTemplateStatus(String templateStatus) {
        this.templateStatus = templateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_template_no
     *
     * @return the value of t_pec_template.f_template_no
     *
     * @mbg.generated
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_template_no
     *
     * @param templateNo the value for t_pec_template.f_template_no
     *
     * @mbg.generated
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_current_mirror_no
     *
     * @return the value of t_pec_template.f_current_mirror_no
     *
     * @mbg.generated
     */
    public String getCurrentMirrorNo() {
        return currentMirrorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_current_mirror_no
     *
     * @param currentMirrorNo the value for t_pec_template.f_current_mirror_no
     *
     * @mbg.generated
     */
    public void setCurrentMirrorNo(String currentMirrorNo) {
        this.currentMirrorNo = currentMirrorNo == null ? null : currentMirrorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_template_name
     *
     * @return the value of t_pec_template.f_template_name
     *
     * @mbg.generated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_template_name
     *
     * @param templateName the value for t_pec_template.f_template_name
     *
     * @mbg.generated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_template_description
     *
     * @return the value of t_pec_template.f_template_description
     *
     * @mbg.generated
     */
    public String getTemplateDescription() {
        return templateDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_template_description
     *
     * @param templateDescription the value for t_pec_template.f_template_description
     *
     * @mbg.generated
     */
    public void setTemplateDescription(String templateDescription) {
        this.templateDescription = templateDescription == null ? null : templateDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_created_time
     *
     * @return the value of t_pec_template.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_created_time
     *
     * @param createdTime the value for t_pec_template.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_modified_time
     *
     * @return the value of t_pec_template.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_modified_time
     *
     * @param modifiedTime the value for t_pec_template.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pec_template.f_operater_name
     *
     * @return the value of t_pec_template.f_operater_name
     *
     * @mbg.generated
     */
    public String getOperaterName() {
        return operaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pec_template.f_operater_name
     *
     * @param operaterName the value for t_pec_template.f_operater_name
     *
     * @mbg.generated
     */
    public void setOperaterName(String operaterName) {
        this.operaterName = operaterName == null ? null : operaterName.trim();
    }
}