package com.parses.dao.mapper.csc;

import com.parses.dao.model.csc.MerchantMemberEntity;
import org.apache.ibatis.annotations.Param;

public interface MerchantMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    int insert(MerchantMemberEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    int insertSelective(MerchantMemberEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    MerchantMemberEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MerchantMemberEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csc_merchant_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MerchantMemberEntity row);

    MerchantMemberEntity selectByMerchantCodeAndMemberType(@Param("merchantCode")String merchantCode, @Param("merchantType") String merchantType);
}