package com.parses.dao.mapper;

import com.parses.dao.model.CapitalPricingEntity;

import java.util.List;

public interface CapitalPricingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    int insert(CapitalPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    int insertSelective(CapitalPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    CapitalPricingEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CapitalPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_pricing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CapitalPricingEntity row);

    int batchInsert(List<CapitalPricingEntity> list);
}