package com.parses.dao.mapper;

import com.parses.dao.model.CapitalEntity;

public interface CapitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    int insert(CapitalEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    int insertSelective(CapitalEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    CapitalEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CapitalEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CapitalEntity row);

    int insertCapital(CapitalEntity row);
}