package com.parses.dao.mapper;

import com.parses.dao.model.CapitalTemplateEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CapitalTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    int insert(CapitalTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    int insertSelective(CapitalTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    CapitalTemplateEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CapitalTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_capital_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CapitalTemplateEntity row);

    List<CapitalTemplateEntity> selectByCapitalCode(String capitalCode);

    List<CapitalTemplateEntity> selectByCapitalCodeAndMatchTargetCode(@Param("capitalCode") String capitalCode, @Param("matchTargetCode") String matchTargetCode);
}