package com.parses.dao.mapper;

import com.parses.dao.model.ElementDataEntity;

import java.util.List;

public interface ElementDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    int insert(ElementDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    int insertSelective(ElementDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    ElementDataEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ElementDataEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_element_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ElementDataEntity row);

    int batchInsert(List<ElementDataEntity> list);
}