package com.parses.dao.mapper;

import com.parses.dao.model.FeeTemplateEntity;

import java.util.List;

public interface FeeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    int insert(FeeTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    int insertSelective(FeeTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    FeeTemplateEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FeeTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_fee_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FeeTemplateEntity row);

    List<FeeTemplateEntity> selectByTemplateNo(String templateNo);
}