package com.parses.dao.mapper;

import com.parses.dao.model.PricingFeeEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PricingFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    int insert(PricingFeeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    int insertSelective(PricingFeeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    PricingFeeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PricingFeeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_pricing_fee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PricingFeeEntity row);

    int batchInsert(List<PricingFeeEntity> list);

    PricingFeeEntity selectByPricingNoAndFeeCode(@Param("pricingNo") String pricingNo,@Param("feeCode") String feeCode);

}