package com.parses.dao.mapper;

import com.parses.dao.model.ProductPricingEntity;

import java.util.List;

public interface ProductPricingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    int insert(ProductPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    int insertSelective(ProductPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    ProductPricingEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductPricingEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product_pricing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductPricingEntity row);

    ProductPricingEntity selectByPricingNo(String pricingNo);

    int batchInsert(List<ProductPricingEntity> list);
}