package com.parses.dao.mapper;

import com.parses.dao.model.ProductEntity;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    int insert(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    ProductEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductEntity row);

    ProductEntity selectByProductCode(String productCode);
}