package com.parses.dao.mapper;

import com.parses.dao.model.TemplateElementEntity;

import java.util.List;

public interface TemplateElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    int insert(TemplateElementEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    int insertSelective(TemplateElementEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    TemplateElementEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TemplateElementEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template_element
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TemplateElementEntity row);

    List<TemplateElementEntity> selectByTemplateMirrorNo(String templateMirrorNo);
}