package com.parses.dao.mapper;

import com.parses.dao.model.TemplateEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    int insert(TemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    int insertSelective(TemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    TemplateEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pec_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TemplateEntity row);

    List<TemplateEntity> selectBySourceType(String sourceType);

    TemplateEntity selectBySourceTypeAndTemplateNo(@Param("sourceType") String sourceType, @Param("templateNo") String templateNo);

}