package com.parses.dao.model.csc;

import java.util.Date;

public class MerchantMemberEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_merchant_type
     *
     * @mbg.generated
     */
    private String merchantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_merchant_no
     *
     * @mbg.generated
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_member_name
     *
     * @mbg.generated
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_member_type
     *
     * @mbg.generated
     */
    private String memberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_member_no
     *
     * @mbg.generated
     */
    private String memberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_allow_pre_settle
     *
     * @mbg.generated
     */
    private String allowPreSettle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_member_fullname
     *
     * @mbg.generated
     */
    private String memberFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_created_user
     *
     * @mbg.generated
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_csc_merchant_member.f_modified_user
     *
     * @mbg.generated
     */
    private String modifiedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_id
     *
     * @return the value of t_csc_merchant_member.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_id
     *
     * @param id the value for t_csc_merchant_member.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_merchant_type
     *
     * @return the value of t_csc_merchant_member.f_merchant_type
     *
     * @mbg.generated
     */
    public String getMerchantType() {
        return merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_merchant_type
     *
     * @param merchantType the value for t_csc_merchant_member.f_merchant_type
     *
     * @mbg.generated
     */
    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_merchant_code
     *
     * @return the value of t_csc_merchant_member.f_merchant_code
     *
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_merchant_code
     *
     * @param merchantCode the value for t_csc_merchant_member.f_merchant_code
     *
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_merchant_no
     *
     * @return the value of t_csc_merchant_member.f_merchant_no
     *
     * @mbg.generated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_merchant_no
     *
     * @param merchantNo the value for t_csc_merchant_member.f_merchant_no
     *
     * @mbg.generated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_member_name
     *
     * @return the value of t_csc_merchant_member.f_member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_member_name
     *
     * @param memberName the value for t_csc_merchant_member.f_member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_member_type
     *
     * @return the value of t_csc_merchant_member.f_member_type
     *
     * @mbg.generated
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_member_type
     *
     * @param memberType the value for t_csc_merchant_member.f_member_type
     *
     * @mbg.generated
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_member_no
     *
     * @return the value of t_csc_merchant_member.f_member_no
     *
     * @mbg.generated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_member_no
     *
     * @param memberNo the value for t_csc_merchant_member.f_member_no
     *
     * @mbg.generated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_created_time
     *
     * @return the value of t_csc_merchant_member.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_created_time
     *
     * @param createdTime the value for t_csc_merchant_member.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_modified_time
     *
     * @return the value of t_csc_merchant_member.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_modified_time
     *
     * @param modifiedTime the value for t_csc_merchant_member.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_allow_pre_settle
     *
     * @return the value of t_csc_merchant_member.f_allow_pre_settle
     *
     * @mbg.generated
     */
    public String getAllowPreSettle() {
        return allowPreSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_allow_pre_settle
     *
     * @param allowPreSettle the value for t_csc_merchant_member.f_allow_pre_settle
     *
     * @mbg.generated
     */
    public void setAllowPreSettle(String allowPreSettle) {
        this.allowPreSettle = allowPreSettle == null ? null : allowPreSettle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_member_fullname
     *
     * @return the value of t_csc_merchant_member.f_member_fullname
     *
     * @mbg.generated
     */
    public String getMemberFullname() {
        return memberFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_member_fullname
     *
     * @param memberFullname the value for t_csc_merchant_member.f_member_fullname
     *
     * @mbg.generated
     */
    public void setMemberFullname(String memberFullname) {
        this.memberFullname = memberFullname == null ? null : memberFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_created_user
     *
     * @return the value of t_csc_merchant_member.f_created_user
     *
     * @mbg.generated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_created_user
     *
     * @param createdUser the value for t_csc_merchant_member.f_created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_csc_merchant_member.f_modified_user
     *
     * @return the value of t_csc_merchant_member.f_modified_user
     *
     * @mbg.generated
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_csc_merchant_member.f_modified_user
     *
     * @param modifiedUser the value for t_csc_merchant_member.f_modified_user
     *
     * @mbg.generated
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }
}